
HEADERS += \
    $$PWD/commonuiset/collapsewidget/collapsewidget.h \
    $$PWD/commonuiset/controls/iplineedit.h \
    $$PWD/commonuiset/factorywidget/factorywidget.h \
    $$PWD/commonuiset/imagegraphics/imagegraphicsitem.h \
    $$PWD/commonuiset/imagegraphics/imagegraphicsscene.h \
    $$PWD/commonuiset/imagegraphics/imagegraphicsview.h \
    $$PWD/commonuiset/lineedit/lineedit.h \
    $$PWD/commonuiset/lineedit/namelineedit.h \
    $$PWD/commonuiset/messagedialog/messagedialog.h \
    $$PWD/commonuiset/messagedialog/messagedialogtitlebar.h \
    $$PWD/commonuiset/table/customheaderview.h \
    $$PWD/commonuiset/table/outputtablewidget.h \
    $$PWD/commonuiset/table/tablemodel.h \
    $$PWD/commonuiset/table/tablewidget.h \
    $$PWD/commonuiset/listwidget/listwidgetitem.h \
    $$PWD/commonuiset/tipwidget/tipwidget.h \
    $$PWD/commonuiset/arrowwidget/arrowwidget.h \
    $$PWD/commonuiset/titlebar/titlebar.h \
    $$PWD/commonuiset/toastwidget/toastwidget.h \
    $$PWD/commonuiset/waitingdialog/waitingdialog.h \
    $$PWD/commonuiset/dialog/dialog.h \
    $$PWD/configuiset/commsetting/commobjeditdlg.h \
    $$PWD/configuiset/commsetting/commobjpage.h \
    $$PWD/configuiset/commsetting/commsettingpage.h \
    $$PWD/configuiset/commsetting/commtestpage.h \
    $$PWD/configuiset/commsetting/commtestsession.h \
    $$PWD/configuiset/commsetting/protocolpage.h \
    $$PWD/configuiset/commsetting/serialportinfopage.h \
    $$PWD/configuiset/commsetting/serialportpage.h \
    $$PWD/configuiset/commsetting/tcpclientpage.h \
    $$PWD/configuiset/commsetting/tcpserverpage.h \
    $$PWD/configuiset/commsetting/udppage.h \
    $$PWD/configuiset/commsetting/session.h \
    $$PWD/configuiset/imagesourcesetting/imagesourcesettingpage.h \
    $$PWD/configuiset/lightsetting/lightinfo.h \
    $$PWD/configuiset/lightsetting/lightsetting.h \
    $$PWD/configuiset/lightsetting/lightsettingdialog.h \
    $$PWD/configuiset/lightsetting/lightsettingpage.h \
    $$PWD/configuiset/lightsetting/opticalparamssettingwidget.h \
    $$PWD/configuiset/modelsetting/addmodelwidget.h \
    $$PWD/configuiset/imagesourcesetting/imagesourcesettingwidget.h \
    $$PWD/configuiset/modelsetting/modelitem.h \
    $$PWD/configuiset/modelsetting/modelsetting.h \
    $$PWD/configuiset/outputsetting/adddatapackdialog.h \
    $$PWD/configuiset/outputsetting/datapacksettingdialog.h \
    $$PWD/configuiset/outputsetting/datapackwidget.h \
    $$PWD/configuiset/outputsetting/editstringdialog.h \
    $$PWD/configuiset/outputsetting/outputsettingpage.h \
    $$PWD/configuiset/outputsetting/outputsettingstack.h \
    $$PWD/configuiset/savesetting/savesetting.h \
    $$PWD/configuiset/settingpage.h \
    $$PWD/mainuiset/aboutdialog.h \
    $$PWD/mainuiset/commstatuswidget.h \
    $$PWD/mainuiset/imageviews/doubleviewswidget.h \
    $$PWD/mainuiset/imageviews/errordialog.h \
    $$PWD/mainuiset/imageviews/fourviewswidget.h \
    $$PWD/mainuiset/imageviews/imageview.h \
    $$PWD/mainuiset/imageviews/multiviewswidget.h \
    $$PWD/mainuiset/imageviews/singleviewwidget.h \
    $$PWD/mainuiset/imageviews/threeviewswidget.h \
    $$PWD/mainuiset/imageviews/viewitemwidget.h \
    $$PWD/mainuiset/imageviews/viewslistwidget.h \
    $$PWD/mainuiset/imageviews/viewstatusbar.h \
    $$PWD/mainuiset/imageviews/viewtoolbar.h \
    $$PWD/mainuiset/lightstatuswidget.h \
    $$PWD/mainuiset/mainframe.h \
    $$PWD/mainuiset/operationalcontrolwidget.h \
    $$PWD/mainuiset/statuslisttooltip.h \
    $$PWD/mainuiset/statuswidget.h \
    $$PWD/mainuiset/titlebarwidget.h \
    $$PWD/mainuiset/statisticswidget.h \
    $$PWD/mainuiset/datalistwidget.h \
    $$PWD/mainuiset/logwidget.h \
    $$PWD/configuiset/camerasetting/camerasettingpage.h \
    $$PWD/configuiset/configdialog.h \
    $$PWD/configuiset/modelsetting/modelsettingpage.h \
    $$PWD/configuiset/camerasetting/camerasetting.h \
    $$PWD/configuiset/viewsetting/viewsetting.h \
    $$PWD/configuiset/savesetting/savesettingpage.h \
    $$PWD/configuiset/systemsetting/systemsettingpage.h \
    $$PWD/configuiset/viewsetting/viewsettingpage.h \
    $$PWD/configuiset/modelsetting/modelstack.h


SOURCES += \
    $$PWD/commonuiset/collapsewidget/collapsewidget.cpp \
    $$PWD/commonuiset/controls/iplineedit.cpp \
    $$PWD/commonuiset/factorywidget/factorywidget.cpp \
    $$PWD/commonuiset/imagegraphics/imagegraphicsitem.cpp \
    $$PWD/commonuiset/imagegraphics/imagegraphicsscene.cpp \
    $$PWD/commonuiset/imagegraphics/imagegraphicsview.cpp \
    $$PWD/commonuiset/lineedit/lineedit.cpp \
    $$PWD/commonuiset/lineedit/namelineedit.cpp \
    $$PWD/commonuiset/messagedialog/messagedialog.cpp \
    $$PWD/commonuiset/messagedialog/messagedialogtitlebar.cpp \
    $$PWD/commonuiset/table/customheaderview.cpp \
    $$PWD/commonuiset/table/outputtablewidget.cpp \
    $$PWD/commonuiset/table/tablemodel.cpp \
    $$PWD/commonuiset/table/tablewidget.cpp \
    $$PWD/commonuiset/listwidget/listwidgetitem.cpp \
    $$PWD/commonuiset/tipwidget/tipwidget.cpp \
    $$PWD/commonuiset/arrowwidget/arrowwidget.cpp \
    $$PWD/commonuiset/titlebar/titlebar.cpp \
    $$PWD/commonuiset/toastwidget/toastwidget.cpp \
    $$PWD/commonuiset/waitingdialog/waitingdialog.cpp \
    $$PWD/commonuiset/dialog/dialog.cpp \
    $$PWD/configuiset/commsetting/commobjeditdlg.cpp \
    $$PWD/configuiset/commsetting/commobjpage.cpp \
    $$PWD/configuiset/commsetting/commsettingpage.cpp \
    $$PWD/configuiset/commsetting/commtestpage.cpp \
    $$PWD/configuiset/commsetting/commtestsession.cpp \
    $$PWD/configuiset/commsetting/serialportinfopage.cpp \
    $$PWD/configuiset/commsetting/serialportpage.cpp \
    $$PWD/configuiset/commsetting/tcpclientpage.cpp \
    $$PWD/configuiset/commsetting/tcpserverpage.cpp \
    $$PWD/configuiset/commsetting/udppage.cpp \
    $$PWD/configuiset/commsetting/session.cpp \
    $$PWD/configuiset/imagesourcesetting/imagesourcesettingpage.cpp \
    $$PWD/configuiset/lightsetting/lightinfo.cpp \
    $$PWD/configuiset/lightsetting/lightsetting.cpp \
    $$PWD/configuiset/lightsetting/lightsettingdialog.cpp \
    $$PWD/configuiset/lightsetting/lightsettingpage.cpp \
    $$PWD/configuiset/lightsetting/opticalparamssettingwidget.cpp \
    $$PWD/configuiset/modelsetting/addmodelwidget.cpp \
    $$PWD/configuiset/imagesourcesetting/imagesourcesettingwidget.cpp \
    $$PWD/configuiset/modelsetting/modelitem.cpp \
    $$PWD/configuiset/modelsetting/modelsetting.cpp \
    $$PWD/configuiset/outputsetting/adddatapackdialog.cpp \
    $$PWD/configuiset/outputsetting/datapacksettingdialog.cpp \
    $$PWD/configuiset/outputsetting/datapackwidget.cpp \
    $$PWD/configuiset/outputsetting/editstringdialog.cpp \
    $$PWD/configuiset/outputsetting/outputsettingpage.cpp \
    $$PWD/configuiset/outputsetting/outputsettingstack.cpp \
    $$PWD/configuiset/savesetting/savesetting.cpp \
    $$PWD/configuiset/settingpage.cpp \
    $$PWD/mainuiset/aboutdialog.cpp \
    $$PWD/mainuiset/commstatuswidget.cpp \
    $$PWD/mainuiset/imageviews/doubleviewswidget.cpp \
    $$PWD/mainuiset/imageviews/errordialog.cpp \
    $$PWD/mainuiset/imageviews/fourviewswidget.cpp \
    $$PWD/mainuiset/imageviews/imageview.cpp \
    $$PWD/mainuiset/imageviews/multiviewswidget.cpp \
    $$PWD/mainuiset/imageviews/singleviewwidget.cpp \
    $$PWD/mainuiset/imageviews/threeviewswidget.cpp \
    $$PWD/mainuiset/imageviews/viewitemwidget.cpp \
    $$PWD/mainuiset/imageviews/viewslistwidget.cpp \
    $$PWD/mainuiset/imageviews/viewstatusbar.cpp \
    $$PWD/mainuiset/imageviews/viewtoolbar.cpp \
    $$PWD/mainuiset/lightstatuswidget.cpp \
    $$PWD/mainuiset/mainframe.cpp \
    $$PWD/mainuiset/statuslisttooltip.cpp \
    $$PWD/mainuiset/statuswidget.cpp \
    $$PWD/mainuiset/titlebarwidget.cpp \
    $$PWD/mainuiset/operationalcontrolwidget.cpp \
    $$PWD/mainuiset/statisticswidget.cpp \
    $$PWD/mainuiset/datalistwidget.cpp \
    $$PWD/mainuiset/logwidget.cpp \
    $$PWD/configuiset/camerasetting/camerasettingpage.cpp \
    $$PWD/configuiset/configdialog.cpp \
    $$PWD/configuiset/modelsetting/modelsettingpage.cpp \
    $$PWD/configuiset/camerasetting/camerasetting.cpp \
    $$PWD/configuiset/viewsetting/viewsetting.cpp \
    $$PWD/configuiset/savesetting/savesettingpage.cpp \
    $$PWD/configuiset/systemsetting/systemsettingpage.cpp \
    $$PWD/configuiset/viewsetting/viewsettingpage.cpp \
    $$PWD/configuiset/modelsetting/modelstack.cpp \


FORMS += \
    $$PWD/commonuiset/collapsewidget/collapsewidget.ui \
    $$PWD/commonuiset/factorywidget/factorywidget.ui \
    $$PWD/commonuiset/messagedialog/messagedialog.ui \
    $$PWD/commonuiset/table/outputtablewidget.ui \
    $$PWD/commonuiset/table/tablewidget.ui \
    $$PWD/commonuiset/tipwidget/tipwidget.ui \
    $$PWD/commonuiset/toastwidget/toastwidget.ui \
    $$PWD/commonuiset/waitingdialog/waitingdialog.ui \
    $$PWD/commonuiset/dialog/dialog.ui \
    $$PWD/configuiset/commsetting/commobjpage.ui \
    $$PWD/configuiset/commsetting/commsettingpage.ui \
    $$PWD/configuiset/commsetting/commtestpage.ui \
    $$PWD/configuiset/commsetting/serialportinfopage.ui \
    $$PWD/configuiset/commsetting/serialportpage.ui \
    $$PWD/configuiset/commsetting/tcpclientpage.ui \
    $$PWD/configuiset/commsetting/tcpserverpage.ui \
    $$PWD/configuiset/commsetting/udppage.ui \
    $$PWD/configuiset/imagesourcesetting/imagesourcesettingpage.ui \
    $$PWD/configuiset/lightsetting/lightinfo.ui \
    $$PWD/configuiset/lightsetting/lightsetting.ui \
    $$PWD/configuiset/lightsetting/lightsettingdialog.ui \
    $$PWD/configuiset/lightsetting/lightsettingpage.ui \
    $$PWD/configuiset/lightsetting/opticalparamssettingwidget.ui \
    $$PWD/configuiset/modelsetting/addmodelwidget.ui \
    $$PWD/configuiset/imagesourcesetting/imagesourcesettingwidget.ui \
    $$PWD/configuiset/modelsetting/modelitem.ui \
    $$PWD/configuiset/modelsetting/modelsetting.ui \
    $$PWD/configuiset/outputsetting/adddatapackdialog.ui \
    $$PWD/configuiset/outputsetting/datapacksettingdialog.ui \
    $$PWD/configuiset/outputsetting/datapackwidget.ui \
    $$PWD/configuiset/outputsetting/editstringdialog.ui \
    $$PWD/configuiset/outputsetting/outputsettingpage.ui \
    $$PWD/configuiset/outputsetting/outputsettingstack.ui \
    $$PWD/configuiset/savesetting/savesetting.ui \
    $$PWD/mainuiset/aboutdialog.ui \
    $$PWD/mainuiset/commstatuswidget.ui \
    $$PWD/mainuiset/imageviews/doubleviewswidget.ui \
    $$PWD/mainuiset/imageviews/errordialog.ui \
    $$PWD/mainuiset/imageviews/fourviewswidget.ui \
    $$PWD/mainuiset/imageviews/imageview.ui \
    $$PWD/mainuiset/imageviews/multiviewswidget.ui \
    $$PWD/mainuiset/imageviews/singleviewwidget.ui \
    $$PWD/mainuiset/imageviews/threeviewswidget.ui \
    $$PWD/mainuiset/imageviews/viewitemwidget.ui \
    $$PWD/mainuiset/imageviews/viewslistwidget.ui \
    $$PWD/mainuiset/imageviews/viewstatusbar.ui \
    $$PWD/mainuiset/imageviews/viewtoolbar.ui \
    $$PWD/mainuiset/lightstatuswidget.ui \
    $$PWD/mainuiset/mainframe.ui \
    $$PWD/mainuiset/statuslisttooltip.ui \
    $$PWD/mainuiset/statuswidget.ui \
    $$PWD/mainuiset/titlebarwidget.ui \
    $$PWD/mainuiset/operationalcontrolwidget.ui \
    $$PWD/mainuiset/statisticswidget.ui \
    $$PWD/mainuiset/datalistwidget.ui \
    $$PWD/mainuiset/logwidget.ui \
    $$PWD/configuiset/camerasetting/camerasettingpage.ui \
    $$PWD/configuiset/configdialog.ui \
    $$PWD/configuiset/modelsetting/modelsettingpage.ui \
    $$PWD/configuiset/camerasetting/camerasetting.ui \
    $$PWD/configuiset/viewsetting/viewsetting.ui \
    $$PWD/configuiset/savesetting/savesettingpage.ui \
    $$PWD/configuiset/systemsetting/systemsettingpage.ui \
    $$PWD/configuiset/viewsetting/viewsettingpage.ui \
    $$PWD/configuiset/modelsetting/modelstack.ui \


TRANSLATIONS += \
           $$PWD/translations/smore_vilab_en.ts \
           $$PWD/translations/smore_vilab_zh-cn.ts

RC_ICONS = $$PWD/images/logo.ico
